# Generated by Django 3.2.7 on 2021-10-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210930_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title']},
        ),
    ]
